### ISSUE TITLE
Unexpected behavior when calling .cluster() multiple times while using grid 

### ISSUE THREAD

**Issue by wraseman** [joshhjacobson/parasol#13]
@joshhjacobson, I am creating an example in which a slider is used to define the number of clusters: 
![image](https://user-images.githubusercontent.com/14048152/47582919-023da300-d913-11e8-9bf3-a8c4bfae8f34.png)
It's working well, just one hiccup. Every time the data is re-clustered, a new cluster column is added to the grid. The way I've implemented it is equivalent to this:
```javascript
ps.attachGrid({container: '#grid'})
  .linked()
  .cluster({k: 4})
  .cluster({k: 3})
  .cluster({k: 2})
  .cluster({k: 3})
```
I think this could be fixed in cluster.js between lines 104 and 106. Could you take a stab at it when you have a chance? The same would probably have to be done for aggregateScores.js but I'm not positive.

**Comment by joshhjacobson** [comment]
Good catch! Yeah I think this should be a simple fix. I'll try to get to it over the weekend.
