### ISSUE TITLE
How to specify the axis limits？

### ISSUE THREAD

**Issue by Liwi1979** [joshhjacobson/parasol#31]
How to specify the axis limits？ For  example,  how to change [10  50] to [0  100]?

**Comment by wraseman** [comment]
@Liwi1979, thanks for your question. Specifying axis limits is available through the Parcoords API that is available through Parasol by using the ```.scale()``` method. 

For instance, to specify the name of an axis called "Percent" on the 1st parallel coordinate plot (i.e., chart) and change the extent from [10, 50] to [0, 100], you would use the following command: 

```ps.charts[0].scale('Percent", [0, 100])```

For a more detailed example, see its usage in the [LRGV Parasol app](https://github.com/ParasolJS/parasoljs.github.io/blob/master/demo/lrgv.html). I"ve also updated the Parasol API on the Wiki page to include more detail on the ```.scale()``` method.
