### ISSUE TITLE
Visible axes example not working

### ISSUE THREAD

**Issue by wraseman** [joshhjacobson/parasol#6]
Hi Josh, 

As you know, there is a bug in the hide/show axes (visible_axes.html) where either the "Hide 'Year'" and "Show 'Year'" buttons work or the "Hide Partitions" and "Show Partitions" work, but they don't work together. From what I can tell, once you click one of the 'Year' buttons, the other buttons get disconnected from the 2nd and 3rd charts.

**Comment by wraseman** [comment]
It looks like this issue has been resolved with the "hide and show axes with example" commit

**Comment by joshhjacobson** [comment]
Interesting... yeah I remember it was working for me when I last touched on it. There's still the weird problem with one of the axes in the first chart that I mentioned in the script's comments. I'll submit a separate issue with more details once I figure out what's going on.
